### ISSUE TITLE
ph3 lesson 2-21

### ISSUE THREAD

**Issue by bluebear94** [Sparen/sparen.github.io#1]
> One thing to note, however, is the presence of brackets [ and ] in strTextIn and strTextView. Unfortunately, I highly recommend removing them and replacing them with spaces " ", because they are highly problematic (Danmakufu recognizes them as special characters, etc.). Simply remove them and add two empty spaces before your new 'End'.

As far as I know, `[osb]` displays `[` and `[csb]` displays `]`; you can replace the offending characters with the formatting code, or disable syntactic analysis altogether (`ObjText_SetSyntacticAnalysis(text, false)`). It might be worth noting this fact.

**Comment by Sparen** [comment]
If that's so, it's good to know. Thanks for telling me.
